steps:
- name: "gcr.io/cloud-builders/gcloud"
  waitFor: ["-"]
  args:
  - gcloud
  - functions
  - deploy
  - attribution-explore
  - --region=us-west1
  - --source=.
  - --trigger-http
  - --runtime=RUNTIME
  dir: "bot_attribution_explore"
options:
  logging: CLOUD_LOGGING_ONLY