steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - attribution-explore
  - --region=us-west1
  - --source=.
  - --trigger-http
  - --runtime=RUNTIME
  dir: "bot_attribution_explore"
options:
  logging: CLOUD_LOGGING_ONLY